import 'package:meta/meta.dart';

import '../extensions/data_class_extensions.dart';
import '../tdapi.dart';

/// Points to a file
@immutable
sealed class InputFile extends TdObject {
  const InputFile();

  static const String constructor = 'inputFile';

  @override
  String getConstructor() => constructor;

  /// Inherited by:
  /// [InputFileGenerated]
  /// [InputFileId]
  /// [InputFileLocal]
  /// [InputFileRemote]
  static InputFile? fromJson(Map<String, dynamic>? json) {
    if (json == null) {
      return null;
    }

    switch (json['@type']) {
      case InputFileGenerated.constructor:
        return InputFileGenerated.fromJson(json);

      case InputFileId.constructor:
        return InputFileId.fromJson(json);

      case InputFileLocal.constructor:
        return InputFileLocal.fromJson(json);

      case InputFileRemote.constructor:
        return InputFileRemote.fromJson(json);

      default:
        return null;
    }
  }

  @override
  bool operator ==(Object other) => overriddenEquality(other);

  @override
  int get hashCode => overriddenHashCode;
}

/// A file generated by the application. The application must handle updates
/// updateFileGenerationStart and updateFileGenerationStop to generate the
/// file when asked by TDLib
@immutable
final class InputFileGenerated extends InputFile {
  InputFileGenerated({
    required this.originalPath,
    required this.conversion,
    required this.expectedSize,
  });

  /// [originalPath] Local path to a file from which the file is generated. The
  /// path doesn't have to be a valid path and is used by TDLib only to detect
  /// name and MIME type of the generated file
  final String originalPath;

  /// [conversion] String specifying the conversion applied to the original
  /// file; must be persistent across application restarts. Conversions
  /// beginning with '#' are reserved for internal TDLib usage
  final String conversion;

  /// [expectedSize] Expected size of the generated file, in bytes; pass 0 if
  /// unknown
  final int expectedSize;

  static const String constructor = 'inputFileGenerated';

  @override
  String getConstructor() => constructor;

  @override
  Map<String, dynamic> toJson() => <String, dynamic>{
    'original_path': originalPath,
    'conversion': conversion,
    'expected_size': expectedSize,
    '@type': constructor,
  };

  static InputFileGenerated? fromJson(Map<String, dynamic>? json) {
    if (json == null) {
      return null;
    }

    return InputFileGenerated(
      originalPath: (json['original_path'] as String?) ?? '',
      conversion: (json['conversion'] as String?) ?? '',
      expectedSize: (json['expected_size'] as int?) ?? 0,
    );
  }

  @override
  bool operator ==(Object other) => overriddenEquality(other);

  @override
  int get hashCode => overriddenHashCode;
}

/// A file defined by its unique identifier
@immutable
final class InputFileId extends InputFile {
  InputFileId({required this.id});

  /// [id] Unique file identifier
  final int id;

  static const String constructor = 'inputFileId';

  @override
  String getConstructor() => constructor;

  @override
  Map<String, dynamic> toJson() => <String, dynamic>{
    'id': id,
    '@type': constructor,
  };

  static InputFileId? fromJson(Map<String, dynamic>? json) {
    if (json == null) {
      return null;
    }

    return InputFileId(id: (json['id'] as int?) ?? 0);
  }

  @override
  bool operator ==(Object other) => overriddenEquality(other);

  @override
  int get hashCode => overriddenHashCode;
}

/// A file defined by a local path
@immutable
final class InputFileLocal extends InputFile {
  InputFileLocal({required this.path});

  /// [path] Local path to the file
  final String path;

  static const String constructor = 'inputFileLocal';

  @override
  String getConstructor() => constructor;

  @override
  Map<String, dynamic> toJson() => <String, dynamic>{
    'path': path,
    '@type': constructor,
  };

  static InputFileLocal? fromJson(Map<String, dynamic>? json) {
    if (json == null) {
      return null;
    }

    return InputFileLocal(path: (json['path'] as String?) ?? '');
  }

  @override
  bool operator ==(Object other) => overriddenEquality(other);

  @override
  int get hashCode => overriddenHashCode;
}

/// A file defined by its remote identifier. The remote identifier is
/// guaranteed to be usable only if the corresponding file is still accessible
/// to the user and known to TDLib. For example, if the file is from a
/// message, then the message must be not deleted and accessible to the user.
/// If the file database is disabled, then the corresponding object with the
/// file must be preloaded by the application
@immutable
final class InputFileRemote extends InputFile {
  InputFileRemote({required this.id});

  /// [id] Remote file identifier
  final String id;

  static const String constructor = 'inputFileRemote';

  @override
  String getConstructor() => constructor;

  @override
  Map<String, dynamic> toJson() => <String, dynamic>{
    'id': id,
    '@type': constructor,
  };

  static InputFileRemote? fromJson(Map<String, dynamic>? json) {
    if (json == null) {
      return null;
    }

    return InputFileRemote(id: (json['id'] as String?) ?? '');
  }

  @override
  bool operator ==(Object other) => overriddenEquality(other);

  @override
  int get hashCode => overriddenHashCode;
}
