name: Native Prebuilt Build
on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      target:
        required: true
        type: string
      artifact-name:
        required: true
        type: string
jobs:
  build:
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get --no-example
      - run: dart run native_prebuilt build --target ${{ inputs.target }} --output built-library --from-source
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ inputs.artifact-name }}
          path: built-library/${{ inputs.target }}/
          if-no-files-found: ignore
